# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 240, 851, 241))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(84, 84, 84);\n"
"     border-bottom: 1px solid #000000;\n"
"     border-left: 0px solid #000000;\n"
"    border-top: 1px solid #000000;\n"
"    border-right: 1px solid #000000;\n"
"    font-size: 9pt;\n"
"    padding : 2px;\n"
"    }\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #000000;\n"
"    font: 9pt \"MS Shell Dlg 2\"    \n"
"    }\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    border-top: 1px solid #ffffff;\n"
"    }\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-left: 1px solid #ffffff;\n"
"    border-top: 1px solid #78beff;\n"
"    }\n"
"\n"
" QTableView QTableCornerButton::section {\n"
"    background: #aaff7f;\n"
"    border: 2px outset #aaff7f;\n"
"     }\n"
"\n"
"\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit_query = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_query.setGeometry(QtCore.QRect(80, 30, 681, 31))
        self.textEdit_query.setObjectName("textEdit_query")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(770, 30, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setObjectName("pushButton_search")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_imported = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_imported.setGeometry(QtCore.QRect(160, 90, 111, 31))
        self.comboBox_imported.setObjectName("comboBox_imported")
        self.comboBox_imported.addItem("")
        self.comboBox_imported.addItem("")
        self.comboBox_imported.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_links_found = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_links_found.setGeometry(QtCore.QRect(160, 140, 111, 31))
        self.comboBox_links_found.setObjectName("comboBox_links_found")
        self.comboBox_links_found.addItem("")
        self.comboBox_links_found.addItem("")
        self.comboBox_links_found.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(690, 210, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_total_results = QtWidgets.QLabel(self.centralwidget)
        self.label_total_results.setGeometry(QtCore.QRect(790, 210, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_total_results.setFont(font)
        self.label_total_results.setObjectName("label_total_results")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 500, 961, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(820, 170, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(999)
        self.spinBox.setObjectName("spinBox")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(680, 170, 141, 31))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TITLE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SITE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LINKS FOUND"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "IMPORTED"))
        self.label.setText(_translate("MainWindow", "Input"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Filter IMPORTED"))
        self.comboBox_imported.setItemText(0, _translate("MainWindow", "No"))
        self.comboBox_imported.setItemText(1, _translate("MainWindow", "Yes"))
        self.comboBox_imported.setItemText(2, _translate("MainWindow", "Show all"))
        self.label_3.setText(_translate("MainWindow", "Filter LINKS FOUND"))
        self.comboBox_links_found.setItemText(0, _translate("MainWindow", "Yes"))
        self.comboBox_links_found.setItemText(1, _translate("MainWindow", "No"))
        self.comboBox_links_found.setItemText(2, _translate("MainWindow", "Show all"))
        self.label_4.setText(_translate("MainWindow", "Results found:"))
        self.label_total_results.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "MongoDB:"))
        self.checkBox.setText(_translate("MainWindow", "Limit search results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
